'use strict';

/**
 * ConversationBuffer — rolling conversation history shared across all model calls.
 *
 * Every dialogue call receives the buffer injected after the system prompt,
 * so any model — Ollama tiny or Claude — has the same conversational context.
 *
 * When the buffer exceeds maxTurns the caller supplies a summary string
 * (generated by a cheap quick-tier call) and the oldest half is replaced.
 */

class ConversationBuffer {
  constructor(maxTurns = 20) {
    this.maxTurns = Math.max(4, maxTurns);
    this._turns   = [];    // [{role:'user'|'assistant', content, ts}]
    this._summary = null;  // compressed summary of older turns
  }

  // ── Write ─────────────────────────────────────────────────────────────────

  /** Append a player or bot turn. Call after every exchange. */
  push(role, content) {
    if (!content?.trim()) return;
    this._turns.push({ role, content: content.trim(), ts: Date.now() });
  }

  /**
   * Called with a summary string once needsSummarization is true.
   * Drops the oldest half and stores the summary as a leading system note.
   */
  applySummary(summaryText) {
    const keep   = Math.ceil(this._turns.length / 2);
    this._turns  = this._turns.slice(-keep);
    this._summary = summaryText.trim();
  }

  clear() {
    this._turns  = [];
    this._summary = null;
  }

  updateMaxTurns(n) { this.maxTurns = Math.max(4, n); }

  // ── Read ──────────────────────────────────────────────────────────────────

  get length()              { return this._turns.length; }
  get needsSummarization()  { return this._turns.length > this.maxTurns; }

  /**
   * Returns messages ready to inject after the system prompt.
   * @param {number} maxRecent  how many of the most-recent turns to include
   */
  getMessages(maxRecent = this.maxTurns) {
    const msgs = [];
    if (this._summary) {
      msgs.push({ role: 'system', content: `[Earlier in this conversation: ${this._summary}]` });
    }
    const slice = this._turns.slice(-Math.max(1, maxRecent));
    for (const t of slice) msgs.push({ role: t.role, content: t.content });
    return msgs;
  }

  /**
   * Returns the oldest half as plain text for summarization.
   * Pass the resulting summary to applySummary().
   */
  getOldestHalfText() {
    const half  = Math.floor(this._turns.length / 2);
    const chunk = this._turns.slice(0, half);
    return chunk.map(t => `${t.role === 'user' ? 'Player' : 'Bud'}: ${t.content}`).join('\n');
  }
}

module.exports = ConversationBuffer;
