'use strict';

/**
 * ConversationBuffer — rolling conversation history shared across all model calls.
 *
 * Every dialogue call receives the buffer injected after the system prompt,
 * so any model — Ollama tiny or Claude — has the same conversational context.
 *
 * When the buffer exceeds maxTurns the caller supplies a summary string
 * (generated by a cheap quick-tier call) and the oldest half is replaced.
 *
 * Persistence: save() / load() write to data/conversation-buffer.json.
 * Turns older than MAX_AGE_HOURS are discarded on load to avoid stale context.
 */

const fs   = require('fs');
const path = require('path');
const { resolveDataFile } = require('../paths');

const BUFFER_FILE    = resolveDataFile('conversation-buffer.json');
const MAX_AGE_HOURS  = 72; // discard turns older than 3 days
const MAX_AGE_MS     = MAX_AGE_HOURS * 3_600_000;

class ConversationBuffer {
  constructor(maxTurns = 20, companionName = 'Bud') {
    this.maxTurns      = Math.max(4, maxTurns);
    this.companionName = companionName;
    this._turns        = [];   // [{role:'user'|'assistant', content, ts}]
    this._summary      = null; // compressed summary of older turns
  }

  updateMaxTurns(n) { this.maxTurns = Math.max(4, n); }

  // ── Write ─────────────────────────────────────────────────────────────────

  /** Append a player or bot turn. Call after every exchange. */
  push(role, content) {
    if (!content?.trim()) return;
    this._turns.push({ role, content: content.trim(), ts: Date.now() });
  }

  /**
   * Called with a summary string once needsSummarization is true.
   * Drops the oldest half and stores the summary as a leading system note.
   */
  applySummary(summaryText) {
    const keep   = Math.ceil(this._turns.length / 2);
    this._turns  = this._turns.slice(-keep);
    this._summary = summaryText.trim();
  }

  clear() {
    this._turns  = [];
    this._summary = null;
  }

  // ── Read ──────────────────────────────────────────────────────────────────

  get length()              { return this._turns.length; }
  get needsSummarization()  { return this._turns.length > this.maxTurns; }

  /**
   * Returns messages ready to inject after the system prompt.
   * @param {number} maxRecent  how many of the most-recent turns to include
   */
  getMessages(maxRecent = this.maxTurns) {
    const msgs = [];
    if (this._summary) {
      msgs.push({ role: 'system', content: `[Earlier in this conversation: ${this._summary}]` });
    }
    const slice = this._turns.slice(-Math.max(1, maxRecent));
    for (const t of slice) msgs.push({ role: t.role, content: t.content });
    return msgs;
  }

  /**
   * Returns the oldest half as plain text for summarization.
   * Pass the resulting summary to applySummary().
   */
  getOldestHalfText() {
    const half  = Math.floor(this._turns.length / 2);
    const chunk = this._turns.slice(0, half);
    const name  = this.companionName || 'Bud';
    return chunk.map(t => `${t.role === 'user' ? 'Player' : name}: ${t.content}`).join('\n');
  }

  // ── Persistence ───────────────────────────────────────────────────────────

  /**
   * Persist the current buffer to disk.
   * Called on bot disconnect so history survives a restart.
   */
  save() {
    try {
      fs.mkdirSync(path.dirname(BUFFER_FILE), { recursive: true });
      fs.writeFileSync(BUFFER_FILE, JSON.stringify({
        companionName: this.companionName,
        summary:       this._summary,
        turns:         this._turns,
        savedAt:       Date.now(),
      }, null, 2), 'utf-8');
    } catch { /* non-fatal */ }
  }

  /**
   * Load a previously saved buffer from disk.
   * Discards turns older than MAX_AGE_HOURS so context stays relevant.
   * Call once after constructing BotManager.
   */
  load() {
    try {
      if (!fs.existsSync(BUFFER_FILE)) return;
      const raw = JSON.parse(fs.readFileSync(BUFFER_FILE, 'utf-8'));
      if (!raw || typeof raw !== 'object') return;

      const cutoff = Date.now() - MAX_AGE_MS;

      // Keep turns that are recent enough
      const turns = (Array.isArray(raw.turns) ? raw.turns : [])
        .filter(t => typeof t.ts === 'number' ? t.ts > cutoff : true);

      this._turns   = turns;
      // Only restore summary if the buffer itself is still warm
      this._summary = turns.length > 0 ? (raw.summary || null) : null;
    } catch { /* non-fatal — start fresh if file is corrupt */ }
  }

  /** How many turns are loaded, and how old the oldest one is. */
  loadedStats() {
    if (!this._turns.length) return { turns: 0, oldestMinsAgo: null };
    const oldest = Math.min(...this._turns.map(t => t.ts || Date.now()));
    return {
      turns:         this._turns.length,
      oldestMinsAgo: Math.round((Date.now() - oldest) / 60_000),
    };
  }
}

module.exports = ConversationBuffer;
